// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWjKJliojgd3N56_cRhIlwDZyNYIEvO8',
    appId: '1:38164806058:web:cbb221a4239f5e85f0d3d3',
    messagingSenderId: '38164806058',
    projectId: 'experience-share-35b48',
    authDomain: 'experience-share-35b48.firebaseapp.com',
    storageBucket: 'experience-share-35b48.appspot.com',
    measurementId: 'G-T797XCZLVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjPLwoonzt_PWMTk-20wi-WUlCf2ueCE',
    appId: '1:38164806058:android:657ec9059840dfb7f0d3d3',
    messagingSenderId: '38164806058',
    projectId: 'experience-share-35b48',
    storageBucket: 'experience-share-35b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL90ysfzGJGX6Cwzh6nW5mrc9EpkBUKFk',
    appId: '1:38164806058:ios:7e9fb3d5a6142606f0d3d3',
    messagingSenderId: '38164806058',
    projectId: 'experience-share-35b48',
    storageBucket: 'experience-share-35b48.appspot.com',
    iosBundleId: 'com.example.gee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL90ysfzGJGX6Cwzh6nW5mrc9EpkBUKFk',
    appId: '1:38164806058:ios:7e9fb3d5a6142606f0d3d3',
    messagingSenderId: '38164806058',
    projectId: 'experience-share-35b48',
    storageBucket: 'experience-share-35b48.appspot.com',
    iosBundleId: 'com.example.gee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkWjKJliojgd3N56_cRhIlwDZyNYIEvO8',
    appId: '1:38164806058:web:8b6fd371a891d1a2f0d3d3',
    messagingSenderId: '38164806058',
    projectId: 'experience-share-35b48',
    authDomain: 'experience-share-35b48.firebaseapp.com',
    storageBucket: 'experience-share-35b48.appspot.com',
    measurementId: 'G-SV9MWF8DE5',
  );
}
